[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://translate.googleusercontent.com"
    Access-Control-Allow-Credentials = "true"
    Content-Security-Policy = "frame-ancestors https://translate.google.com"
    X-Frame-Options = "ALLOW-FROM https://translate.google.com"
